#!/usr/bin/env bun
/**
 * Builds the frontend and inlines the result into a generated TypeScript module.
 *
 * Why inline rather than serve from disk: on Vercel the app runs under the Bun
 * *backend framework* builder, which routes every request to the server
 * function and does NOT publish a static directory to the CDN. `includeFiles`
 * is ignored for framework entrypoints, so the built assets never reach the
 * function's filesystem. Bundling them into a module the server imports is the
 * one delivery path that survives — rolldown compiles the module straight into
 * the function.
 *
 * Outputs both:
 *   - public/                          for `bun run start` and any static host
 *   - web/frontend-assets.generated.ts imported by the server (git-ignored)
 */
import { readdir, rm } from "node:fs/promises";

const OUT_DIR = "public";
const MODULE_PATH = "web/frontend-assets.generated.ts";

function contentType(name: string): string {
  if (name.endsWith(".html")) return "text/html; charset=utf-8";
  if (name.endsWith(".css")) return "text/css; charset=utf-8";
  if (name.endsWith(".js")) return "text/javascript; charset=utf-8";
  if (name.endsWith(".map")) return "application/json; charset=utf-8";
  if (name.endsWith(".svg")) return "image/svg+xml";
  if (name.endsWith(".png")) return "image/png";
  if (name.endsWith(".woff2")) return "font/woff2";
  return "application/octet-stream";
}

await rm(OUT_DIR, { recursive: true, force: true });

const result = await Bun.build({
  entrypoints: ["web/index.html"],
  outdir: OUT_DIR,
  minify: true,
  sourcemap: "none",
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  throw new Error("frontend build failed");
}

const files = await readdir(OUT_DIR);
const assets: Record<string, { type: string; base64: string }> = {};
for (const name of files) {
  const bytes = await Bun.file(`${OUT_DIR}/${name}`).bytes();
  assets[`/${name}`] = {
    type: contentType(name),
    base64: Buffer.from(bytes).toString("base64"),
  };
}

const module = `// GENERATED by bundle-frontend.ts — do not edit, do not commit.
export interface Asset {
  type: string;
  base64: string;
}

/** Built frontend files, keyed by request path (e.g. "/index.html"). */
export const ASSETS: Record<string, Asset> = ${JSON.stringify(assets)};
`;

await Bun.write(MODULE_PATH, module);

const total = Object.values(assets).reduce((sum, a) => sum + a.base64.length, 0);
console.log(
  `bundled ${Object.keys(assets).length} assets → ${MODULE_PATH} (${(total / 1024).toFixed(0)} KB base64)`,
);
